SET standard_conforming_strings = OFF;
DROP TABLE IF EXISTS "public"."hqdenata" CASCADE;
DELETE FROM geometry_columns WHERE f_table_name = 'hqdenata' AND f_table_schema = 'public';
BEGIN;
CREATE TABLE "public"."hqdenata" ( "ogc_fid" SERIAL, CONSTRAINT "hqdenata_pk" PRIMARY KEY ("ogc_fid") );
SELECT AddGeometryColumn('public','hqdenata','wkb_geometry',4326,'POINT',2);
CREATE INDEX "hqdenata_wkb_geometry_geom_idx" ON "public"."hqdenata" USING GIST ("wkb_geometry");
ALTER TABLE "public"."hqdenata" ADD COLUMN "id" NUMERIC(10,0);
ALTER TABLE "public"."hqdenata" ADD COLUMN "hq_number" NUMERIC(10,0);
ALTER TABLE "public"."hqdenata" ADD COLUMN "vehiclesqt" NUMERIC(10,0);
INSERT INTO "public"."hqdenata" ("wkb_geometry" , "id", "hq_number", "vehiclesqt") VALUES ('0101000020E6100000CE54D13C5F3822C0DC321BEBEF5C4340', 1, NULL, NULL);
COMMIT;
